### ISSUE TITLE
Enable partial update of attributes

### ISSUE THREAD

**Issue by edwards33** [ScienceDb/express_route_gen_js#3]
In create (POST) and update (PUT) set only those attributes that are actually sent as query parameters (data in the request).

Adjust the partial `views/partials/set_attributes.ejs`.
So far it generates lines like these:
````
taxon.updateAttributes({
                name: req.body.name,
                taxonomic_level: req.body.taxonomic_level,
                parent_id: req.body.parent_id
            })
````
Adjust the code generator to produce lines like these:
````
req.body.intersectKeys(taxonAttributes)
````
Note, that the above ` intersectKeys`  does not yet exists.

**Comment by asishallab** [comment]
Actually doing an intersection between `Object.keys(req.body)` and the model attributes should be the best approach

**Comment by edwards33** [comment]
Pull following branch: '10-Enable-partial-update-of-attributes'
